# Generated by Django 4.2.1 on 2023-05-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_link', models.CharField(max_length=64, null=True)),
                ('long_link', models.CharField(max_length=1024)),
            ],
        ),
    ]
